//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chinook.View.Converters.PrettyDistanceConverter.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DistanceHelperStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DistanceHelperStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chinook.View.Converters.PrettyDistanceConverter.Resources.DistanceHelperStrings", typeof(DistanceHelperStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about one mile.
        /// </summary>
        internal static string Imperial_AboutOneMile_ShortString {
            get {
                return ResourceManager.GetString("Imperial_AboutOneMile_ShortString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about one mile.
        /// </summary>
        internal static string Imperial_AboutOneMileString {
            get {
                return ResourceManager.GetString("Imperial_AboutOneMileString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0} ft.
        /// </summary>
        internal static string Imperial_Feet_ShortFormatString {
            get {
                return ResourceManager.GetString("Imperial_Feet_ShortFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0} feet.
        /// </summary>
        internal static string Imperial_FeetFormatString {
            get {
                return ResourceManager.GetString("Imperial_FeetFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a few feet.
        /// </summary>
        internal static string Imperial_Here_ShortFormatString {
            get {
                return ResourceManager.GetString("Imperial_Here_ShortFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a few feet.
        /// </summary>
        internal static string Imperial_HereFormatString {
            get {
                return ResourceManager.GetString("Imperial_HereFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0} mi.
        /// </summary>
        internal static string Imperial_Miles_ShortFormatString {
            get {
                return ResourceManager.GetString("Imperial_Miles_ShortFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0} miles.
        /// </summary>
        internal static string Imperial_MilesFormatString {
            get {
                return ResourceManager.GetString("Imperial_MilesFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0.#} ft.
        /// </summary>
        internal static string Imperial_NearFeet_ShortFormatString {
            get {
                return ResourceManager.GetString("Imperial_NearFeet_ShortFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0.#} feet.
        /// </summary>
        internal static string Imperial_NearFeetFormatString {
            get {
                return ResourceManager.GetString("Imperial_NearFeetFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0.#} mi.
        /// </summary>
        internal static string Imperial_NearMiles_ShortFormatString {
            get {
                return ResourceManager.GetString("Imperial_NearMiles_ShortFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0.#} miles.
        /// </summary>
        internal static string Imperial_NearMilesFormatString {
            get {
                return ResourceManager.GetString("Imperial_NearMilesFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0} ft.
        /// </summary>
        internal static string Imperial_OneFoot_ShortFormatString {
            get {
                return ResourceManager.GetString("Imperial_OneFoot_ShortFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0} foot.
        /// </summary>
        internal static string Imperial_OneFootFormatString {
            get {
                return ResourceManager.GetString("Imperial_OneFootFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0} mi.
        /// </summary>
        internal static string Imperial_OneMile_ShortFormatString {
            get {
                return ResourceManager.GetString("Imperial_OneMile_ShortFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0} mile.
        /// </summary>
        internal static string Imperial_OneMileFormatString {
            get {
                return ResourceManager.GetString("Imperial_OneMileFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0.#} mi.
        /// </summary>
        internal static string Imperial_UnderOneMile_ShortString {
            get {
                return ResourceManager.GetString("Imperial_UnderOneMile_ShortString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0.#} mile.
        /// </summary>
        internal static string Imperial_UnderOneMileString {
            get {
                return ResourceManager.GetString("Imperial_UnderOneMileString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about one kilometer.
        /// </summary>
        internal static string Metric_AboutOneKilometer_ShortString {
            get {
                return ResourceManager.GetString("Metric_AboutOneKilometer_ShortString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about one kilometer.
        /// </summary>
        internal static string Metric_AboutOneKilometerString {
            get {
                return ResourceManager.GetString("Metric_AboutOneKilometerString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to less than a meter.
        /// </summary>
        internal static string Metric_Here_ShortFormatString {
            get {
                return ResourceManager.GetString("Metric_Here_ShortFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to less than a meter.
        /// </summary>
        internal static string Metric_HereFormatString {
            get {
                return ResourceManager.GetString("Metric_HereFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0} km.
        /// </summary>
        internal static string Metric_Kilometers_ShortFormatString {
            get {
                return ResourceManager.GetString("Metric_Kilometers_ShortFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0} kilometers.
        /// </summary>
        internal static string Metric_KilometersFormatString {
            get {
                return ResourceManager.GetString("Metric_KilometersFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0} m.
        /// </summary>
        internal static string Metric_Meters_ShortFormatString {
            get {
                return ResourceManager.GetString("Metric_Meters_ShortFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0} meters.
        /// </summary>
        internal static string Metric_MetersFormatString {
            get {
                return ResourceManager.GetString("Metric_MetersFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0.#} km.
        /// </summary>
        internal static string Metric_NearKilometers_ShortFormatString {
            get {
                return ResourceManager.GetString("Metric_NearKilometers_ShortFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0.#} kilometers.
        /// </summary>
        internal static string Metric_NearKilometersFormatString {
            get {
                return ResourceManager.GetString("Metric_NearKilometersFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0.#} m.
        /// </summary>
        internal static string Metric_NearMeters_ShortFormatString {
            get {
                return ResourceManager.GetString("Metric_NearMeters_ShortFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0.#} meters.
        /// </summary>
        internal static string Metric_NearMetersFormatString {
            get {
                return ResourceManager.GetString("Metric_NearMetersFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0} km.
        /// </summary>
        internal static string Metric_OneKilometer_ShortFormatString {
            get {
                return ResourceManager.GetString("Metric_OneKilometer_ShortFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0} kilometer.
        /// </summary>
        internal static string Metric_OneKilometerFormatString {
            get {
                return ResourceManager.GetString("Metric_OneKilometerFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0} m.
        /// </summary>
        internal static string Metric_OneMeter_ShortFormatString {
            get {
                return ResourceManager.GetString("Metric_OneMeter_ShortFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0} meter.
        /// </summary>
        internal static string Metric_OneMeterFormatString {
            get {
                return ResourceManager.GetString("Metric_OneMeterFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0.#} km.
        /// </summary>
        internal static string Metric_UnderOneKilometer_ShortString {
            get {
                return ResourceManager.GetString("Metric_UnderOneKilometer_ShortString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0.#} kilometer.
        /// </summary>
        internal static string Metric_UnderOneKilometerString {
            get {
                return ResourceManager.GetString("Metric_UnderOneKilometerString", resourceCulture);
            }
        }
    }
}
